-- Dropping DATA SHARE if exists
USE ROLE ACCOUNTADMIN;

DROP SHARE IF EXISTS PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;

CREATE SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE COMMENT = 'PROVIDER_DB_SNOWFLAKE_SECURE_SHARE';

SHOW SHARES STARTS WITH 'PROVIDER_DB_SNOWFLAKE_SECURE_SHARE';

-- Creating a database
USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE PROVIDER_DB COMMENT = 'Provider Database' DATA_RETENTION_TIME_IN_DAYS = 1;

-- Creating a Sales Table
CREATE OR REPLACE TABLE PROVIDER_DB.PUBLIC.SALES (
        id              NUMBER,
        country_id      VARCHAR,
        sales_date      DATE,
        sales_amount    NUMBER
);

-- Adding some records to the table sales
USE WAREHOUSE SCS;
INSERT INTO PROVIDER_DB.PUBLIC.SALES (id, country_id, sales_date, sales_amount) VALUES
 (1,'DE','2021-09-01',10901),
 (2,'DE','2021-10-01',11001),
 (3,'NL','2021-09-01',20901),
 (4,'NL','2021-10-01',21001),
 (5,'US','2021-09-01',30901),
 (6,'US','2021-10-01',31001);

-- Selecting off the new table sales
SELECT * FROM PROVIDER_DB.PUBLIC.SALES;

-- ************ Add database to share ************
USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE PROVIDER_DB TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;
GRANT USAGE ON SCHEMA PROVIDER_DB.PUBLIC TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;
GRANT SELECT ON TABLE PROVIDER_DB.PUBLIC.SALES TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;

ALTER SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE ADD ACCOUNTS = <DATA_SHARING_ACCOUNT_ID>;

SHOW GRANTS TO SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE;

-- ********** ADD SHARE IN CONSUMER **********

-- DB name: PROVIDER_DB

-- ********** ADD SHARE IN CONSUMER **********

-- Adding a new record in the provider
USE ROLE SYSADMIN;
INSERT INTO PROVIDER_DB.PUBLIC.SALES (id, country_id, sales_date, sales_amount) VALUES
 (20,'DE','2021-09-01',10901);

-- Update last record
UPDATE PROVIDER_DB.PUBLIC.SALES SET sales_amount = 10000 WHERE id = 20; -- What happens to the consumer?

-- Advance: Creating a Row Access Policy
USE ROLE SYSADMIN;
CREATE OR REPLACE TABLE PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING (
    COUNTRY_ID      VARCHAR,
    ACCOUNT_NAME    VARCHAR
);

-- Inserting some records into the country_policy_mapping table
TRUNCATE TABLE PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING;
SELECT CURRENT_ACCOUNT();
INSERT INTO PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING(COUNTRY_ID, ACCOUNT_NAME) VALUES
  ('DE','ZSC83610'),
  ('NL','ZSC83610'),
  ('US','ZSC83610'),
  ('US','VJC71364');

-- Selecting off the new table country_policy_mapping
SELECT * FROM PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING;

-- Creating a row access policy for the sales table
CREATE OR REPLACE ROW ACCESS POLICY PROVIDER_DB.PUBLIC.SIMPLE_POLICY AS (country_id VARCHAR) RETURNS BOOLEAN ->
  'ZSC83610' = CURRENT_ACCOUNT()
      OR EXISTS (
            SELECT 1 FROM PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING mpt
            WHERE ACCOUNT_NAME = CURRENT_ACCOUNT()
             AND mpt.country_id = country_id
          )
;

-- Adding the row access policy to the sales table
ALTER TABLE PROVIDER_DB.PUBLIC.SALES
  ADD ROW ACCESS POLICY PROVIDER_DB.PUBLIC.SIMPLE_POLICY ON (COUNTRY_ID);

USE ROLE SYSADMIN;

-- ALTER TABLE PROVIDER_DB.PUBLIC.SALES
--   DROP ROW ACCESS POLICY PROVIDER_DB.PUBLIC.SIMPLE_POLICY;

-- DROP ROW ACCESS POLICY IF EXISTS PROVIDER_DB.PUBLIC.SIMPLE_POLICY;

-- Selecting off-the-table sales (should return 6 records for the provider)
SELECT * FROM PROVIDER_DB.PUBLIC.SALES; -- Now what happens to the consumer?

-- INSERT INTO TABLE PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING 
INSERT INTO PROVIDER_DB.PUBLIC.COUNTRY_POLICY_MAPPING(COUNTRY_ID, ACCOUNT_NAME) VALUES
  ('NL','VJC71364');

-- What happens to the consumer?

-- REVOKE ACCESS
USE ROLE ACCOUNTADMIN;
ALTER SHARE PROVIDER_DB_SNOWFLAKE_SECURE_SHARE REMOVE ACCOUNTS = <DATA_SHARING_ACCOUNT_ID>;
