USE ROLE SYSADMIN;
USE DATABASE SNOWFLAKE_CODE_SAMPLE;
USE SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC;
USE WAREHOUSE SCS;

-- Creating a table out of a sample data
CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER;

SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER;

-- You can change the warehouse size on the fly, be aware this incurs in a cost
ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SET WAREHOUSE_SIZE = XXLARGE;

CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;

ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SET WAREHOUSE_SIZE = XSMALL;

SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.LINEITEM;

-- ***** Different CACHING *****
-- METADATA CACHE
ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SUSPEND;
SELECT MAX(L_SHIPDATE), MIN(L_SHIPDATE) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.LINEITEM;

-- RESULT SET CACHE
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SUSPEND;

SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

-- DISABLE RESULT SET CACHE
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SUSPEND;
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

ALTER SESSION SET USE_CACHED_RESULT = TRUE;
