USE ROLE SYSADMIN;

DROP WAREHOUSE IF EXISTS SNOWFLAKE_CODE_SAMPLE;
DROP DATABASE  IF EXISTS SNOWFLAKE_CODE_SAMPLE CASCADE;

-- Creating a new virtual warehouse with the following properties
CREATE OR REPLACE WAREHOUSE SCS WITH
    WAREHOUSE_SIZE = 'X-SMALL' -- { XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE }
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = ECONOMY -- { STANDARD | ECONOMY }
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE -- { TRUE | FALSE };
    --MAX_CONCURRENCY_LEVEL = <num>
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0 
    STATEMENT_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0
;

USE WAREHOUSE SCS;

-- Creating a new database with the following properties
CREATE OR REPLACE DATABASE SNOWFLAKE_CODE_SAMPLE
    DATA_RETENTION_TIME_IN_DAYS = 2; -- We will discuss what DATA_RETENTION_TIME_IN_DAYS means in futher sessions

USE DATABASE SNOWFLAKE_CODE_SAMPLE;

-- Creating a table out of a sample data
CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER;

SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER;

-- You can change the warehouse size on the fly, be aware this incurs in a cost
ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SET WAREHOUSE_SIZE = XXLARGE;

CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;

ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SET WAREHOUSE_SIZE = XSMALL;

SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.LINEITEM;

-- ***** Different CACHING *****
-- METADATA CACHE
ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SUSPEND;
SELECT MAX(L_SHIPDATE), MIN(L_SHIPDATE) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.LINEITEM;

-- RESULT SET CACHE
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SUSPEND;

SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

-- DISABLE RESULT SET CACHE
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

ALTER WAREHOUSE SNOWFLAKE_CODE_SAMPLE SUSPEND;
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

ALTER SESSION SET USE_CACHED_RESULT = TRUE;
