USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE API INTEGRATION GIT_API_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/domfp13')
  ENABLED = TRUE;

GRANT ALL ON INTEGRATION GIT_API_INTEGRATION TO ROLE PUBLIC;
