-- 1.- Creating a custom role analyst
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE ANALYST
 COMMENT  = 'ANALYST';

USE ROLE SECURITYADMIN;

-- Use VSCODE TO prevent secondary roles

-- 2.- Grant role to user and role SYSADMIN
USE ROLE SECURITYADMIN;
GRANT ROLE ANALYST TO ROLE SYSADMIN;
GRANT ROLE ANALYST TO USER SUPERANALYST;

-- 3.- Granting access to tables
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE SNOWFLAKE_CODE_SAMPLE TO ROLE ANALYST;
GRANT USAGE ON SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE SCS TO ROLE ANALYST;
--GRANT USAGE ON WAREHOUSE SNOWFLAKE_CODE_SAMPLE TO ROLE ANALYST;
