USE ROLE SYSADMIN;
USE WAREHOUSE SCS;
USE DATABASE SNOWFLAKE_CODE_SAMPLE;
USE SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC;

-- Create a stream to track changes to the ACCOUNTS_SCHEMA_EVOLUTION table
CREATE OR REPLACE STREAM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM ON TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
 APPEND_ONLY = TRUE
 SHOW_INITIAL_ROWS = TRUE
 COMMENT = 'Stream to track changes to the ACCOUNTS_SCHEMA_EVOLUTION table';

-- Selecting from STREAMS to verify the stream was created
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM;

SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION;
SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM;

-- Creating a table that will hold a subset of the information, this will demonstrate how to use the stream to populate a table.
CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SILVER (
	ACCESSIBLE_BALANCE NUMBER(8,2),
	ACCOUNT_BALANCE NUMBER(8,2),
	ACCOUNT_STATUS_CODE NUMBER(1,0),
	ACCOUNT_UID VARCHAR(16777216),
	CDIC_HOLD_STATUS_CODE NUMBER(1,0),
	CURRENCY_CODE NUMBER(1,0)
);

SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SILVER;

-- Using the stream to populate the table
BEGIN;
	INSERT INTO SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SILVER
	SELECT ACCESSIBLE_BALANCE, ACCOUNT_BALANCE, ACCOUNT_STATUS_CODE, ACCOUNT_UID, CDIC_HOLD_STATUS_CODE, CURRENCY_CODE 
	FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM;
COMMIT;

SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SILVER; -- Data is loaded into the table
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM; -- Once the stream is used in a transaction, it's going to cause the stream to be consumed.

-- ********* Lets load a new file to the original SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION table and see if the stream picks it up *********
-- NOTICE: THE FILE SNOWBANK_PUBLIC_ACCOUNTS_3.json has been changed in structure.
PUT file://////Users/eplata/Developer/snowflake-code-sample/sql/06-advance-sql/SNOWBANK_PUBLIC_ACCOUNTS_3.json @SNOWFLAKE_CODE_SAMPLE.PUBLIC.JSON_FILES_STAGE;

LIST @SNOWFLAKE_CODE_SAMPLE.PUBLIC.JSON_FILES_STAGE;

-- COPY INTO SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
COPY INTO SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
  FROM @SNOWFLAKE_CODE_SAMPLE.PUBLIC.JSON_FILES_STAGE
  FILE_FORMAT = SNOWFLAKE_CODE_SAMPLE.PUBLIC.FILE_FORMAT_JSON_GENERIC
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  PATTERN = '.*.json.gz'
  PURGE = TRUE;

-- Did the stream pick up the new file?
SELECT * FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM;

-- Loading the data in the stream to the silver table
BEGIN;
	INSERT INTO SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SILVER
	SELECT ACCESSIBLE_BALANCE, ACCOUNT_BALANCE, ACCOUNT_STATUS_CODE, ACCOUNT_UID, CDIC_HOLD_STATUS_CODE, CURRENCY_CODE 
	FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION_STREAM;
COMMIT;

SELECT COUNT(*) FROM SNOWFLAKE_CODE_SAMPLE.PUBLIC.ACCOUNTS_SILVER;
