USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE DBT WITH
    WAREHOUSE_SIZE = 'X-SMALL' -- { XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE }
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = ECONOMY -- { STANDARD | ECONOMY }
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE -- { TRUE | FALSE };
    --MAX_CONCURRENCY_LEVEL = <num>
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0 
    STATEMENT_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0
;

USE ROLE SYSADMIN;
ALTER SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC SET LOG_LEVEL = 'INFO';
ALTER SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA SNOWFLAKE_CODE_SAMPLE.PUBLIC SET METRIC_LEVEL = 'ALL';

-- ADDING INTEGRATION
USE ROLE SYSADMIN;
CREATE OR REPLACE NETWORK RULE SNOWFLAKE_CODE_SAMPLE.PUBLIC.DBT_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('hub.getdbt.com', 'codeload.github.com');

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DBT_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (SNOWFLAKE_CODE_SAMPLE.PUBLIC.DBT_NETWORK_RULE)
  ENABLED = true;
