USE ROLE SYSADMIN;
USE WAREHOUSE DBT;
ALTER WAREHOUSE DBT SET WAREHOUSE_SIZE = 'MEDIUM';

-- CREATE TABLES IN SNOWFLAKE_CODE_SAMPLE.PUBLIC SCHEMA FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10

-- CUSTOMER
CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.RAW_CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER;

-- ORDERS
CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.RAW_ORDERS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS;

-- LINEITEM
CREATE OR REPLACE TABLE SNOWFLAKE_CODE_SAMPLE.PUBLIC.RAW_LINEITEM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM;

ALTER WAREHOUSE DBT SET WAREHOUSE_SIZE = 'X-SMALL';