USE ROLE ANALYST;
SHOW DATABASES;
USE DATABASE SNOWFLAKE_CODE_SAMPLE;
SHOW SCHEMAS; -- ACCOUNT_USAGE schema AND other schemas are NOT visible. By default only ACCOUNTADMIN has access to ACCOUNT_USAGE schema.

-- USING THE ACCOUNTADMIN ROLE
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SCS;
SHOW SCHEMAS IN ACCOUNT; -- ACCOUNT_USAGE AND OTHER SCHEMAS ARE VISIBLE

USE DATABASE SNOWFLAKE;
USE SCHEMA ACCOUNT_USAGE;

SHOW TABLES; -- THIS IS A SNOWFLAKE SHARED DB (FUTURE CONCEPT) IN THIS CASE THE SOURCE OWNER (SNOWFLAKE) IS ONLY ALLOWING TO SEE THE VIEWS FROM A DATABASE.
SHOW VIEWS;
SHOW OBJECTS IN DATABASE SNOWFLAKE;

-- IMPORTANT VIEWS for the SnowproCore Exam
SELECT * FROM WAREHOUSE_METERING_HISTORY LIMIT 10;      -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM METERING_DAILY_HISTORY LIMIT 10;          -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM DATABASE_STORAGE_USAGE_HISTORY LIMIT 10;  -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM ACCESS_HISTORY LIMIT 10;                  -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM QUERY_HISTORY LIMIT 10;                   -- THIS VIEW IS ASKED DURING THE EXAM ********* (UI)

-- LETS EXPLORE THE INFORMATION SCHEMA
USE ROLE SYSADMIN;
USE DATABASE SNOWFLAKE_CODE_SAMPLE;
USE SCHEMA INFORMATION_SCHEMA;
USE WAREHOUSE SCS;
SELECT * FROM INFORMATION_SCHEMA.TABLES LIMIT 10; -- EXPLORE SOME OF THE COLUMNS OF THIS VIEW

SHOW OBJECTS IN SCHEMA INFORMATION_SCHEMA
 ->> SELECT * FROM $1;
