USE ROLE ACCOUNTADMIN;
USE DATABASE ACCOUNTADMIN_MGMT;
USE SCHEMA PUBLIC;
--SHOW SCHEMAS IN DATABASE ACCOUNTADMIN_MGMT;

-- Create the ingress rule
CREATE OR REPLACE NETWORK RULE PG_INGRESS_FROM
  TYPE = IPV4
  VALUE_LIST = ('0.0.0.0/0')
  MODE = POSTGRES_INGRESS;

-- Create the egress rule
-- CREATE OR REPLACE NETWORK RULE PG_EGRESS_TO
--   TYPE = IPV4
--   VALUE_LIST = ('0.0.0.0/0')
--   MODE = POSTGRES_EGRESS;

-- Create a new policy using both rules in its allowed list
CREATE NETWORK POLICY PG_NETWORK_POLICY
  ALLOWED_NETWORK_RULE_LIST = ('PG_INGRESS_FROM')
  COMMENT = 'Traffic to/from';

DROP NETWORK POLICY "OFFICE POLICY EXAMPLE";