USE ROLE ACCOUNTADMIN;

-- Create database & schema
CREATE DATABASE IF NOT EXISTS OPENFLOW;
USE DATABASE OPENFLOW;
CREATE SCHEMA IF NOT EXISTS OPENFLOW;
USE SCHEMA OPENFLOW;

USE ROLE ACCOUNTADMIN;
ALTER SCHEMA IF EXISTS OPENFLOW.PUBLIC ENABLE MANAGED ACCESS;
GRANT ALL ON SCHEMA OPENFLOW.PUBLIC TO ROLE SYSADMIN;

CREATE IMAGE REPOSITORY IF NOT EXISTS OPENFLOW;
GRANT USAGE ON DATABASE OPENFLOW TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA OPENFLOW TO ROLE PUBLIC;
GRANT READ ON IMAGE REPOSITORY OPENFLOW.OPENFLOW.OPENFLOW TO ROLE PUBLIC;

-- Grant create on OpenFlow Data Plane Integration
USE ROLE ACCOUNTADMIN;
GRANT CREATE OPENFLOW DATA PLANE INTEGRATION ON ACCOUNT TO ROLE ACCOUNTADMIN;
GRANT CREATE OPENFLOW RUNTIME INTEGRATION ON ACCOUNT TO ROLE ACCOUNTADMIN;
GRANT CREATE OPENFLOW DATA PLANE INTEGRATION ON ACCOUNT TO ROLE SYSADMIN;
GRANT CREATE OPENFLOW RUNTIME INTEGRATION ON ACCOUNT TO ROLE SYSADMIN;

-- Set default secondary roles for the current user
USE ROLE ACCOUNTADMIN;
BEGIN
  LET u STRING := CURRENT_USER();
  EXECUTE IMMEDIATE
    'ALTER USER IDENTIFIER(''' || u || ''') SET DEFAULT_SECONDARY_ROLES = (''ALL'')';
END;

-- Creating new user to login into Openflow
USE ROLE USERADMIN;
CREATE OR REPLACE USER OPENFLOWUSER
 LOGIN_NAME = 'OPENFLOWUSER'
 PASSWORD = '<CHANGE_ME>'
 MUST_CHANGE_PASSWORD = FALSE
 DEFAULT_ROLE = SYSADMIN
 TYPE = LEGACY_SERVICE;

USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER OPENFLOWUSER;
ALTER USER OPENFLOWUSER SET DEFAULT_SECONDARY_ROLES = ('ALL');

-- Creating user for Openflow to connect to Snowflake
USE ROLE USERADMIN;
CREATE OR REPLACE USER OPENFLOWUSERKEYPAIR
 LOGIN_NAME = 'OPENFLOWUSERKEYPAIR'
 MUST_CHANGE_PASSWORD = FALSE
 DEFAULT_ROLE = SYSADMIN;

-- *************This next commands need to be run in the unix terminal***********
-- openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out openflow_rsa_key.p8 -nocrypt
-- openssl rsa -in openflow_rsa_key.p8 -pubout -out openflow_rsa_key.pub

-- Copy the public key 
ALTER USER OPENFLOWUSERKEYPAIR SET RSA_PUBLIC_KEY = '<PASTE_PUBLIC_KEY_HERE>';
DESC USER OPENFLOWUSERKEYPAIR
 ->> SELECT * FROM $1;

USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER OPENFLOWUSERKEYPAIR;

USE ROLE ACCOUNTADMIN;
USE DATABASE OPENFLOW;
USE SCHEMA PUBLIC;

SHOW NETWORK RULES IN ACCOUNT;

CREATE OR REPLACE NETWORK RULE ALLOW_OPENFLOW_DEPLOYMENT
MODE = INGRESS
TYPE = IPV4
VALUE_LIST = ('0.0.0.0/0');

CREATE OR REPLACE NETWORK POLICY OPENFLOW_NETWORK_POLICY
 ALLOWED_NETWORK_RULE_LIST = (ALLOW_OPENFLOW_DEPLOYMENT);

ALTER USER OPENFLOWUSER SET NETWORK_POLICY = OPENFLOW_NETWORK_POLICY;

-- Run this command to find your currently active network policy and copy the value column
SHOW PARAMETERS LIKE 'NETWORK_POLICY' IN ACCOUNT;

-- CREATING A NEW EVENT TABLE
USE ROLE ACCOUNTADMIN;
GRANT CREATE EVENT TABLE ON SCHEMA OPENFLOW.OPENFLOW TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE EVENT TABLE IF NOT EXISTS OPENFLOW.OPENFLOW.OPENFLOW_EVENTS;

-- Find the Data Plane Integrations
USE ROLE ACCOUNTADMIN;

SHOW OPENFLOW DATA PLANE INTEGRATIONS
 ->> SELECT "name" FROM $1;

ALTER OPENFLOW DATA PLANE INTEGRATION
<CHANGE_ME_WITH_STRING_RETURN_FROM_SHOW_OPENFLOW_DATA_PLANE_INTEGRATIONS>
SET EVENT_TABLE = 'openflow.openflow.openflow_events';

SELECT * FROM OPENFLOW.OPENFLOW.OPENFLOW_EVENTS;
 