-- Create the table for the Aviation API
USE ROLE SYSADMIN;
USE DATABASE OPENFLOW;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE OPENFLOW.PUBLIC.FLIGHT_STATUS (
  V VARIANT
);

CREATE OR REPLACE TABLE OPENFLOW.PUBLIC.ORACLE_CUSTOMERS (
  V VARIANT
);

SELECT * FROM OPENFLOW.PUBLIC.ORACLE_CUSTOMERS;

SELECT * FROM OPENFLOW.PUBLIC.FLIGHT_STATUS;
